# Generated by Django 4.1 on 2024-03-28 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_original_cart_order_strip_pid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='strip_pid',
            new_name='stripe_pid',
        ),
    ]
