# Generated by Django 4.1 on 2024-03-30 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='stove_type',
            new_name='friendly_name',
        ),
        migrations.RemoveField(
            model_name='productfeature',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productfeature',
            name='product_type',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='productfeatures',
            field=models.ManyToManyField(blank=True, to='products.productfeature'),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='price_increment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
